name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: ${{ matrix.toolchain }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, "1.85"]

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: fmt
        if: matrix.toolchain == 'stable'
        run: cargo fmt --check

      - name: clippy
        if: matrix.toolchain == 'stable'
        run: cargo clippy --all-features -- -W clippy::nursery -W clippy::pedantic

      - name: test
        run: cargo test --all-features
